### ISSUE TITLE
Select peripheral component values for LMR14050 buck regulator

### ISSUE THREAD

**Issue by chiplet** [luxas/special-computing-machine#2]
Requirements:

* V_in = ~20V
* V_out = 5.1V
* I_out = 3A

Data sheet: https://www.ti.com/lit/ds/symlink/lmr14050.pdf

## TODO
* Feedback resistor network
  * [x] R_FBT = 100k [digikey](https://www.digikey.fi/product-detail/fi/stackpole-electronics-inc/RMCF0603FT100K/RMCF0603FT100KCT-ND/1943118)
  * [x] R_FBB = 17.4k [digikey](https://www.digikey.fi/product-detail/fi/stackpole-electronics-inc/RMCF0603FT17K4/RMCF0603FT17K4CT-ND/2417949)
* [x] R_T = 84.5k [digikey](https://www.digikey.fi/product-detail/fi/panasonic-electronic-components/ERJ-3EKF8452V/P84-5KHCT-ND/198530)
* [x] C_in [digikey](https://www.digikey.fi/product-detail/fi/kemet/C1206C475K5RACTU/399-11685-1-ND/5119828) x2 in series (Also add a generic 100nF decoupling capacitor with appropriate voltage range close the the chip power pin.)
* [x] C_out [digikey](https://www.digikey.fi/product-detail/fi/taiyo-yuden/EMK325BJ476MM-P/587-5436-1-ND/7067112) x3 in series
* [x] C_boot = 0.1uF [digikey](https://www.digikey.fi/product-detail/fi/yageo/CC0603KRX7R8BB104/311-1341-1-ND/2103125)
* [x] C_ss = 22 nF [digikey](https://www.digikey.fi/product-detail/fi/kemet/C0603C223K5RACTU/399-1280-1-ND/416056)
* [x] L = 8.2uH [digikey](https://www.digikey.fi/product-detail/fi/w%C3%BCrth-elektronik/744771008/732-1207-1-ND/1639268)
* [x] D [digikey](https://www.digikey.fi/product-detail/fi/stmicroelectronics/STPS1230SF/497-18303-1-ND/9696997)

## IO connectors
* [x] V_out to raspi [digikey](https://www.digikey.fi/product-detail/fi/gct/USB4085-GF-A/2073-USB4085-GF-ACT-ND/9859733)
* [x] V_in to Laptop Charger [digikey](https://www.digikey.fi/product-detail/fi/w-rth-elektronik/694106301002/732-5930-ND/5047522)

## Protection circuitry
Reverse polarity protection using a P-MOSFET
* [x] P-FET for reverse polarity protection [digikey](https://www.digikey.fi/product-detail/fi/infineon-technologies/IRLML6344TRPBF/IRLML6344TRPBFCT-ND/2538168)
* [x] 10V zener [digikey](https://www.digikey.fi/product-detail/fi/on-semiconductor/MM3Z10VST1G/MM3Z10VST1GOSCT-ND/687054)
* A generic 100k 0603 resistor

**Comment by chiplet** [comment]
## Notes
### Output Voltage Selection
By using feedback resistor values given in the data sheet example, we get a bit over 5V output at 5A. It is recommended to use 1% tolerance or better and temperature coefficient of 100 ppm or lower divider resistors.

### Frequency Selection
The switching frequency should not matter at the moment, so we can also use the values for 300kHz from the example application. This can be changed in the future if EMC issues arise.

### Soft Start Capacitor
Soft start time does not seem important for this application, using example values.

### Output Diode
Output diode should have a reverse breakdown of about 1.25*V_in and should be able to withstand max current output. I.e. V_br = 25V and I_max = 3A.

### Input Capacitors
A generic 100nF capacitor should be placed close the the chip to suppress high frequency noise.

A separate decent quality 4.7uF is used for compensating for lead inductance from the laptop charger.

### IO Connectors
#### V_out to Raspberry Pi
The connector is only used for power delivery so an affordable USB-C 2.0 with no data lines connected should be adequate.

### Protection
#### Reverse polarity protection
A P-channel MOSFET is used for reverse polarity protection as shown [here](https://www.youtube.com/watch?v=IrB-FPcv1Dc). The input current is approximately 1.5A when both outputs are at 3A so a FET with relatively low R_DS was selected to minimise heat generation.

**Comment by chiplet** [comment]
The design has been finished and documented to this issue.
